defaultPortal: PawelYarko
portals:
  - name: PawelYarko
    portalId: 26122390
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNPys4CpMBIJAA0AAAAA4A0DGJaxugwgkoiKFiju6QwyFGbc2Z1TK9BHU9mFM1k709MJXSkTOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhRgE8lZGa0olwNgfZrOEwA6psTwHUoDZXUxUgBaAA
        expiresAt: '2022-08-12T03:15:45.622Z'
    personalAccessKey: >-
      CiRldTEtYmEwYy05OGQ3LTQzMjktYjZmZC1kOGExYTljNmI3MzIQlrG6DBiSiIoWKhkABeaRgqGoGHYqi9zV3tUOZvM2ZFwmW1pJSgNldTE
