defaultPortal: PawelYarko
portals:
  - name: PawelYarko
    portalId: 26122390
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJH4yOinMBIJAA0AAAAA4A0DGJaxugwgkoiKFiju6QwyFHi8J8Qg5wJNX-MK04lTnmtmN11AOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhQgEJABw-0hsU3Z5JjwORDM6AviWEoDZXUxUgBaAA
        expiresAt: '2022-08-08T10:48:43.285Z'
    personalAccessKey: >-
      CiRldTEtYmEwYy05OGQ3LTQzMjktYjZmZC1kOGExYTljNmI3MzIQlrG6DBiSiIoWKhkABeaRgqGoGHYqi9zV3tUOZvM2ZFwmW1pJSgNldTE
