defaultPortal: PawelYarko
portals:
  - name: PawelYarko
    portalId: 26122390
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJzVs6GnMBIJAA0AAAAA4A0DGJaxugwgkoiKFiju6QwyFEllRT6nsA7eC3sR5Ksh7ZQWngLBOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhTpAXvDnJGa5zXes4zLGQpXDNIQFUoDZXUxUgBaAA
        expiresAt: '2022-08-06T17:21:16.960Z'
    personalAccessKey: >-
      CiRldTEtYmEwYy05OGQ3LTQzMjktYjZmZC1kOGExYTljNmI3MzIQlrG6DBiSiIoWKhkABeaRgqGoGHYqi9zV3tUOZvM2ZFwmW1pJSgNldTE
