defaultPortal: PawelYarko
portals:
  - name: PawelYarko
    portalId: 26122390
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJ6AjJeoMBIJAA0AAAAA4A0DGJaxugwgkoiKFiju6QwyFIzLYDMhOu6knRdTbFlr3zbumqFDOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhSku7EGsV5J-u0svkqHEiuncSq1QUoDZXUxUgBaAA
        expiresAt: '2022-08-09T13:54:51.041Z'
    personalAccessKey: >-
      CiRldTEtYmEwYy05OGQ3LTQzMjktYjZmZC1kOGExYTljNmI3MzIQlrG6DBiSiIoWKhkABeaRgqGoGHYqi9zV3tUOZvM2ZFwmW1pJSgNldTE
