defaultPortal: PawelYarko
portals:
  - name: PawelYarko
    portalId: 26122390
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CPua9ZGoMBIJAA0AAAAA4A0DGJaxugwgkoiKFiju6QwyFKjpYQWduKKojW6AvlNXIbo2uEdZOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhTRb0I8Uug1o0JV977k5gHa9nY9UUoDZXUxUgBaAA
        expiresAt: '2022-08-09T10:53:51.871Z'
    personalAccessKey: >-
      CiRldTEtYmEwYy05OGQ3LTQzMjktYjZmZC1kOGExYTljNmI3MzIQlrG6DBiSiIoWKhkABeaRgqGoGHYqi9zV3tUOZvM2ZFwmW1pJSgNldTE
